# Generated by Django 2.2.11 on 2020-03-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_activity', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeFormat',
        ),
        migrations.AddField(
            model_name='users',
            name='time_format',
            field=models.CharField(default='Asia/Kolkata', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='activityperiods',
            table='activity_periods',
        ),
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
    ]
