# Generated by Django 2.2.11 on 2020-03-28 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_activity', '0002_auto_20200328_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityperiods',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user_activity.Users'),
            preserve_default=False,
        ),
    ]
